api_organization_index:
    pattern:  /index
    methods: [GET]
    defaults: 
        _controller: "app.controller.organization:indexAction"
        _sylius:
            limit: $limit
            sorting:
                id: desc
                
api_organization_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.organization:showAction"