api_pet_index:
    pattern:  /
    methods: [GET]
    defaults: 
        _controller: "app.controller.pet:indexAction"
        _sylius:
            sorting:
                id: desc

api_pet_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.pet:showAction"
