api_petlistener_index:
    pattern:  /
    methods: [GET]
    defaults: 
        _controller: "app.controller.petlistener:indexAction"
        _sylius:
            paginate: false
            limit: false
            sorting:
                id: desc

api_petlistener_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.petlistener:showAction"

api_petlistener_create:
    pattern:  /create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.petlistener:createAction"
        _sylius: 
            form: todasaspatas_apibundle_petlistener

api_petlistener_update:
    pattern:  /{id}/update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.petlistener:updateAction"
        _sylius: 
            form: todasaspatas_apibundle_petlistener

api_petlistener_delete:
    pattern:  /{id}/delete
    methods: [DELETE]
    defaults: 
        _controller: "app.controller.petlistener:deleteAction"
