api_questionmessage_index:
    pattern:  /index
    methods: [GET]
    defaults: 
        _controller: "app.controller.questionmessage:indexByUserAction"
        _sylius: 
            limit: false
            paginate: false
            
api_questionmessage_create:
    pattern:  /create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.questionmessage:createAction"
        _sylius: 
            form: todasaspatas_apibundle_questionmessage
            
api_questionmessage_update:
    pattern:  /{id}/update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.questionmessage:updateAction"
        _sylius: 
            form: todasaspatas_apibundle_questionmessage
            
api_questionmessage_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.questionmessage:showAction"