todasaspatas_web_api_pet_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/pet_public.yml"
    prefix:   /pet
    
todasaspatas_web_api_organization_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/organization_public.yml"
    prefix:   /organization