todasaspatas_web_api_routing_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/routing_public.yml"
    prefix:   /public

todasaspatas_web_api_user:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/user.yml"
    prefix:   /user
    
todasaspatas_web_api_questionmessage:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/questionmessage.yml"
    prefix:   /questionmessage
    
todasaspatas_web_api_adoptionrequestmessage:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/adoptionrequestmessage.yml"
    prefix:   /adoptionrequestmessage