todasaspatas_web_api_text_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/text_public.yml"
    prefix:   /text
    
todasaspatas_web_api_pet_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/pet_public.yml"
    prefix:   /pet
    
todasaspatas_web_api_breed_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/breed_public.yml"
    prefix:   /breed

todasaspatas_web_api_organization_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/organization_public.yml"
    prefix:   /organization

todasaspatas_web_api_user_public:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/api/user_public.yml"
    prefix:   /user