api_profile_show:
    pattern:  /profile
    methods: [GET]
    defaults: 
        _controller: "app.controller.usercommon:profileAction"
        
api_favorite_pet:
    pattern:  /favorite-pet
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.usercommon:profileUpdateAction"
        _sylius: 
            form : todasaspatas_apibundle_favorite_pet
            
api_profile_update:
    pattern:  /profile-update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.usercommon:profileUpdateAction"
        _sylius: 
            form : todasaspatas_apibundle_usercommon_api