app_user_create:
    pattern:  /create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.usercommon:createAction"
        _sylius: 
            form: todasaspatas_apibundle_usercommon