TodasAsPatas\ApiBundle\Entity\City: 
    properties:
        id: 
            groups: [details, list]
        state: 
            groups: [details, list]
        name: 
            groups: [details, list]
        addresses: 
            exclude: true
            