TodasAsPatas\ApiBundle\Entity\Pet: 
    virtual_properties:
        getSize:
            groups: [list, details]
            serialized_name: size
            type: string
        getAge:
            groups: [list, details]
            serialized_name: age
            type: string
        getGender:
            groups: [list, details]
            serialized_name: gender
            type: string
        getType:
            groups: [list, details]
            serialized_name: type
            type: string
    properties:
        id: 
            groups: [details, list]
        sizeId: 
            groups: [details, list]
        typeId: 
            groups: [details, list]
        profileImageKey: 
            exclude: true
        profileImage: 
            exclude: true
        name: 
            groups: [details, list]
        images: 
            groups: [details]
        organization: 
            groups: [details, list]
        amountFavorite: 
            groups: [details, list]
        displayQuantity: 
            groups: [details, list]
        breeds: 
            groups: [details, list]
        ageId: 
            groups: [details, list]
        genderId: 
            groups: [details, list]
        createdAt: 
            groups: [list, details]
            type: "DateTime<'d/m/Y H:i'>"
        updatedAt: 
            groups: [list, details]
            type: "DateTime<'d/m/Y H:i'>"