TodasAsPatas\ApiBundle\Entity\Breed: 
    properties:
        id: 
            groups: [details, list]
        name: 
            groups: [details, list]
        createdAt: 
            exclude: true
        updatedAt: 
            exclude: true