TodasAsPatas\ApiBundle\Entity\Breed: 
    virtual_properties:
        getType:
            serialized_name: type
            type: string
    properties:
        id: 
            groups: [details, list]
        name: 
            groups: [details, list]
        createdAt: 
            exclude: true
        updatedAt: 
            exclude: true