TodasAsPatas\ApiBundle\Entity\Organization: 
    properties:
        id: 
            groups: [details, list]
        name: 
            groups: [details, list]
        address: 
            groups: [details, list]
        users: 
            exclude: true
        createdAt: 
            exclude: true
        updatedAt: 
            exclude: true