sylius_resource:
    resources:
        app.petimage:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/PetImage
            classes:
                model: TodasAsPatas\ApiBundle\Entity\PetImage
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\PetImageRepository
        app.pet:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/Pet
            classes:
                model: TodasAsPatas\ApiBundle\Entity\Pet
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\PetRepository
        app.breed:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/Breed
            classes:
                model: TodasAsPatas\ApiBundle\Entity\Breed
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\BreedRepository
        app.userorganization:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/UserOrganization
            classes:
                model: TodasAsPatas\ApiBundle\Entity\UserOrganization
                controller: ByteinCoffee\UserBundle\Controller\UserController
                repository: TodasAsPatas\ApiBundle\Entity\UserOrganizationRepository
        app.organization:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/Organization
            classes:
                model: TodasAsPatas\ApiBundle\Entity\Organization
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\OrganizationRepository
        app.useradmin:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/UserAdmin
            classes:
                model: TodasAsPatas\ApiBundle\Entity\UserAdmin
                controller: ByteinCoffee\UserBundle\Controller\UserController
                repository: TodasAsPatas\ApiBundle\Entity\UserAdminRepository
        app.group:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/Group
            classes:
                model: TodasAsPatas\ApiBundle\Entity\Group
                controller: ByteinCoffee\UserBundle\Controller\GroupController
                repository: TodasAsPatas\ApiBundle\Entity\GroupRepository
        app.text:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/Text
            classes:
                model: TodasAsPatas\ApiBundle\Entity\Text
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\TextRepository
        app.country:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/Country
            classes:
                model: TodasAsPatas\ApiBundle\Entity\Country
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\CountryRepository
        app.state:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/State
            classes:
                model: TodasAsPatas\ApiBundle\Entity\State
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\StateRepository
        app.city:
            driver: doctrine/orm
            templates: TodasAsPatasWebBundle:Backend/City
            classes:
                model: TodasAsPatas\ApiBundle\Entity\City
                controller: ByteinCoffee\ExtraBundle\Controller\Controller
                repository: TodasAsPatas\ApiBundle\Entity\CityRepository