security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER :         [ROLE_API]
        ROLE_ADMIN:         [ROLE_USER, ROLE_API]
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, byteincoffee_user]
                
        in_memory:
            memory:
                users:
                    user:  { password: %root_credentials_user%, roles: [ 'ROLE_USER' ] }
                    admin: { password: %root_credentials_admin%, roles: [ 'ROLE_SUPER_ADMIN', 'ROLE_ADMIN' ] }
                    
        byteincoffee_user:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: chain_provider
                #não implementado
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_provider: form.csrf_provider
                check_path: /login_check
                login_path: /login
                default_target_path : /
            logout:       
                path:   /logout
                target: /login
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 
                path:     /
                domain: ~ 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/\w\d*/public, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/, role: ROLE_ADMIN }
