parameters:
    bytein_coffee_user.security.apikey_authenticator.class: ByteinCoffee\UserBundle\Security\ApiKeyAuthenticator
    bytein_coffee_user.security.apikey_user_provider.class: ByteinCoffee\UserBundle\Security\ApiKeyUserProvider
    bytein_coffee_user.controller.resetting.class: ByteinCoffee\UserBundle\Controller\ResettingController
    bytein_coffee_user.mailer.mailer.class: ByteinCoffee\UserBundle\Mailer\Mailer

services:
    bytein_coffee_user.security.apikey_user_provider:
        class: "%bytein_coffee_user.security.apikey_user_provider.class%"
        arguments: ["@fos_user.user_manager"]
        
    bytein_coffee_user.security.apikey_authenticator:
        class: "%bytein_coffee_user.security.apikey_authenticator.class%"
        arguments: ["@bytein_coffee_user.security.apikey_user_provider", "%secret%"]
        
    bytein_coffee_user.mailer.mailer:
        class: "%bytein_coffee_user.mailer.mailer.class%"
        arguments: 
            - @mailer
            - @router
            - @templating
            - confirmation.template: %fos_user.registration.confirmation.template%
              resetting.template: %fos_user.resetting.email.template%
              from_email: 
                  confirmation: %fos_user.registration.confirmation.from_email%
                  resetting: %fos_user.resetting.email.from_email%
            

    bytein_coffee_user.controller.resetting:
        class: %bytein_coffee_user.controller.resetting.class%
        arguments: ["@sylius.controller.configuration_factory", "ByteinCoffeeUserBundle:User"]
        calls:
            - [setContainer, ["@service_container"]]