app_adoptionrequestmessage_index:
    pattern:  /
    methods: [GET]
    defaults: 
        _controller: "app.controller.adoptionrequestmessage:indexAction"
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                id: desc
        
app_adoptionrequestmessage_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.adoptionrequestmessage:showAction"
        
app_adoptionrequestmessage_visualized:
    pattern:  /{id}/visualized
    methods: [PUT]
    defaults: 
        _format: json
        _controller: "app.controller.adoptionrequestmessage:visualizedAction"

app_adoptionrequestmessage_update:
    pattern:  /{id}/update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.adoptionrequestmessage:updateAction"
        _sylius: 
            form: todasaspatas_apibundle_adoptionrequestmessage_response