app_client_index:
    pattern:  /
    methods: [GET]
    defaults: 
        _controller: "app.controller.client:indexAction"
        _sylius:
            sorting:
                id: desc

app_client_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.client:showAction"
        
app_client_create:
    pattern:  /create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.client:createAction"
        _sylius: 
            form: todasaspatas_apibundle_client

app_client_update:
    pattern:  /{id}/update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.client:updateAction"
        _sylius: 
            form: todasaspatas_apibundle_client

app_client_delete:
    pattern:  /{id}/delete
    methods: [DELETE]
    defaults: 
        _controller: "app.controller.client:deleteAction"
