app_country_index:
    pattern:  /
    methods: [GET]
    defaults: 
        _controller: "app.controller.country:indexAction"
        _sylius:
            paginate: false 
            limit: false
            sorting:
                id: desc

app_country_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.country:showAction"

app_country_create:
    pattern:  /create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.country:createAction"
        _sylius: 
            form: todasaspatas_apibundle_country

app_country_update:
    pattern:  /{id}/update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.country:updateAction"
        _sylius: 
            form: todasaspatas_apibundle_country

app_country_delete:
    pattern:  /{id}/delete
    methods: [DELETE]
    defaults: 
        _controller: "app.controller.country:deleteAction"
