app_group_index:
    pattern:  /
    methods: [GET]
    defaults: 
        _controller: "app.controller.group:indexAction"
        _sylius:
            paginate: false
            limit: false 
            sorting:
                id: desc

app_group_show:
    pattern:  /{id}/show
    methods: [GET]
    defaults: 
        _controller: "app.controller.group:showAction"

app_group_create:
    pattern:  /create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.group:createAction"
        _sylius: 
            form: todasaspatas_apibundle_group

app_group_update:
    pattern:  /{id}/update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.group:updateAction"
        _sylius: 
            form: todasaspatas_apibundle_group

app_group_delete:
    pattern:  /{id}/delete
    methods: [DELETE]
    defaults: 
        _controller: "app.controller.group:deleteAction"
