app_petadoption_create:
    pattern:  /create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.petadoption:createAction"
        _sylius: 
            form: todasaspatas_apibundle_petadoption

app_petadoption_delete:
    pattern:  /{id}/delete
    methods: [DELETE]
    defaults: 
        _controller: "app.controller.petadoption:deleteAction"
