app_petadoption_create:
    pattern:  /{petId}/create
    methods: [GET, POST]
    defaults: 
        _controller: "app.controller.petadoption:createAction"
        _sylius: 
            form: todasaspatas_apibundle_petadoption
            redirect:
                route: app_pet_show
                parameters: { id: resource.pet.id }

app_petadoption_update:
    pattern:  /{id}/update
    methods: [GET, PUT]
    defaults: 
        _controller: "app.controller.petadoption:updateAction"
        _sylius: 
            form: todasaspatas_apibundle_petadoption


app_petadoption_delete:
    pattern:  /{petId}/{id}/delete
    methods: [DELETE]
    defaults: 
        _controller: "app.controller.petadoption:deleteAction"
        _sylius: 
            redirect:
                route: app_pet_show
                parameters: { id: $petId }
