todasaspatas_web_backend_useradmin_profile:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/useradmin_profile.yml"
    prefix:   /profile

todasaspatas_web_backend_useradmin:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/useradmin.yml"
    prefix:   /useradmin

todasaspatas_web_backend_group:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/group.yml"
    prefix:   /group
        
todasaspatas_web_backend_text:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/text.yml"
    prefix:   /text
        
todasaspatas_web_backend_city:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/city.yml"
    prefix:   /city
    
todasaspatas_web_backend_state:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/state.yml"
    prefix:   /state
    
todasaspatas_web_backend_country:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/country.yml"
    prefix:   /country

todasaspatas_web_api_documentation:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/api_documentation.yml"
    prefix:   /documentation/api
        
todasaspatas_web_backend_home:
    path: /
    defaults: 
        _controller: TodasAsPatasWebBundle:Backend/Home:index
        
todasaspatas_web_backend_user:
    resource: "@TodasAsPatasWebBundle/Resources/config/routing/backend/user.yml"
    prefix:   /
    
datatable_pt_BR:
    pattern:  /datatable/translation/pt_br.json
    methods: [GET]
    defaults: 
        _controller: "TodasAsPatasWebBundle:Backend/DataTable:ptBR"