TodasAsPatas\ApiBundle\Entity\AbstractMessage:
    type: entity
    table: message
    repositoryClass: TodasAsPatas\ApiBundle\Entity\AbstractMessageRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        adoption_request: TodasAsPatas\ApiBundle\Entity\AdoptionRequestMessage
        question: TodasAsPatas\ApiBundle\Entity\QuestionMessage
    manyToOne:
        user:
            targetEntity: UserCommon
            joinColumn:
                nullable: false
                name: user_id
                referencedColumnName: id
        pet:
            targetEntity: Pet
            joinColumn:
                nullable: false
                name: pet_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        message:
            type: text
        response:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
