TodasAsPatas\ApiBundle\Entity\AccessToken:
    type:  entity
    table: oauth_access_token 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: Client
            joinColumn:
                nullable: false
        user:
            targetEntity: User