TodasAsPatas\ApiBundle\Entity\Breed:
    type: entity
    table: null
    repositoryClass: TodasAsPatas\ApiBundle\Entity\BreedRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        deletedAt:
            type: datetime
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        typeId:
            type: integer
            options: 
                default: 1
    lifecycleCallbacks: {  }
