TodasAsPatas\ApiBundle\Entity\Client:
    type:  entity
    table: oauth_client
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
