TodasAsPatas\ApiBundle\Entity\Country:
    type: entity
    table: null
    repositoryClass: TodasAsPatas\ApiBundle\Entity\CountryRepository
    oneToMany:
        states:
            cascade: ["persist", "remove"]
            targetEntity: State
            mappedBy: country
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
