TodasAsPatas\ApiBundle\Entity\Pet:
    type: entity
    table: null
    repositoryClass: TodasAsPatas\ApiBundle\Entity\PetRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true
    oneToOne:
        adoption:
            targetEntity: PetAdoption
            mappedBy: pet
    oneToMany:
        images:
            cascade: ["persist", "remove"]
            targetEntity: PetImage
            mappedBy: pet
    manyToOne:
        organization:
            targetEntity: Organization
            joinColumn:
                nullable: false
                name: organization_id
                referencedColumnName: id
    manyToMany:
        breeds:
            targetEntity: Breed
            joinTable:
                name: pets_breeds
                joinColumns:
                    pet_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    breed_id:
                        referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        nameCanonical:
            type: string
            length: 255
            options: 
                default: ''
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
        displayQuantity:
            type: integer
            nullable: true
            options:
                default: 0
        amountFavorite:
            type: integer
            nullable: true
            opiotns: 
                default: 0
        sizeId:
            type: integer
        ageId:
            type: integer
        typeId:
            type: integer
            options: 
                default: 1
        genderId:
            type: integer
        history:
            type: text
            nullable: true
        profileImageKey:
            type: string
            length: 255
            nullable: true
            fsi:
                uploadable:
                    targetField: profileImage
                    filesystem: default
    lifecycleCallbacks: {  }
