TodasAsPatas\ApiBundle\Entity\PetAdoption:
    type: entity
    table: null
    repositoryClass: TodasAsPatas\ApiBundle\Entity\PetAdoptionRepository
    oneToOne:
        pet:
            inversedBy: adoption
            targetEntity: Pet
            joinColumn:
                nullable: false
                name: pet_id
                referencedColumnName: id
    manyToOne:
        user:
            targetEntity: UserCommon
            joinColumn:
                name: user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        typeId:
            type: integer
    lifecycleCallbacks: {  }
