TodasAsPatas\ApiBundle\Entity\RefreshToken:
    type:  entity
    table: oauth_refresh_token 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: Client
            joinColumn:
                nullable: false
        user:
            targetEntity: User