TodasAsPatas\ApiBundle\Entity\State:
    type: entity
    table: null
    repositoryClass: TodasAsPatas\ApiBundle\Entity\StateRepository
    oneToMany:
        cities:
            cascade: ["persist", "remove"]
            targetEntity: City
            mappedBy: state
    manyToOne:
        country:
            targetEntity: Country
            inversedBy: states
            joinColumn:
                nullable: false
                name: country_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        acronym:
            type: string
            length: 2
    lifecycleCallbacks: {  }
