TodasAsPatas\ApiBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: TodasAsPatas\ApiBundle\Entity\UserRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        admin: TodasAsPatas\ApiBundle\Entity\UserAdmin
        organization: TodasAsPatas\ApiBundle\Entity\UserOrganization
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
