parameters:
    todasaspatas_api.form_type.user_admin.class: TodasAsPatas\ApiBundle\Form\UserAdminType
    todasaspatas_api.form_type.user_admin_profile.class: TodasAsPatas\ApiBundle\Form\UserAdminProfileType
    todasaspatas_api.form_type.group.class: TodasAsPatas\ApiBundle\Form\GroupType
    todasaspatas_api.form_type.country.class: TodasAsPatas\ApiBundle\Form\CountryType
    todasaspatas_api.form_type.state.class: TodasAsPatas\ApiBundle\Form\StateType
    todasaspatas_api.form_type.state_city.class: TodasAsPatas\ApiBundle\Form\StateCityType
    todasaspatas_api.form_type.city.class: TodasAsPatas\ApiBundle\Form\CityType
    todasaspatas_api.form_type.address.class: TodasAsPatas\ApiBundle\Form\AddressType
    todasaspatas_api.form_type.text.class: TodasAsPatas\ApiBundle\Form\TextType
    todasaspatas_api.form_type.user_organization.class: TodasAsPatas\ApiBundle\Form\UserOrganizationType
    todasaspatas_api.form_type.organization.class: TodasAsPatas\ApiBundle\Form\OrganizationType
    todasaspatas_api.form_type.breed.class: TodasAsPatas\ApiBundle\Form\BreedType
    todasaspatas_api.form_type.pet.class: TodasAsPatas\ApiBundle\Form\PetType
    todasaspatas_api.form_type.pet_image.class: TodasAsPatas\ApiBundle\Form\PetImageType
    todasaspatas_api.form_type.pet_adoption.class: TodasAsPatas\ApiBundle\Form\PetAdoptionType
    todasaspatas_api.form_type.client.class: TodasAsPatas\ApiBundle\Form\ClientType
    todasaspatas_api.form_type.user_common.class: TodasAsPatas\ApiBundle\Form\UserCommonType
    todasaspatas_api.form_type.favorite_pet.class: TodasAsPatas\ApiBundle\Form\FavoritePetType
    todasaspatas_api.form_type.question_message.class: TodasAsPatas\ApiBundle\Form\QuestionMessageType
    todasaspatas_api.form_type.adoption_request_message.class: TodasAsPatas\ApiBundle\Form\AdoptionRequestMessageType
    todasaspatas_api.form_type.pet_listener.class: TodasAsPatas\ApiBundle\Form\PetListenerType
    todasaspatas_api.form_type.question_message_response.class: TodasAsPatas\ApiBundle\Form\QuestionMessageResponseType
    todasaspatas_api.form_type.adoption_request_message_response.class: TodasAsPatas\ApiBundle\Form\AdoptionRequestMessageResponseType
    todasaspatas_api.form_type.user_common_api.class: TodasAsPatas\ApiBundle\Form\UserCommonApiType

services:
    todasaspatas_api.form_type.pet_listener:
        class: "%todasaspatas_api.form_type.pet_listener.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_petlistener }
            
    todasaspatas_api.form_type.adoption_request_message:
        class: "%todasaspatas_api.form_type.adoption_request_message.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_adoptionrequestmessage }
            
    todasaspatas_api.form_type.question_message:
        class: "%todasaspatas_api.form_type.question_message.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_questionmessage }
            
    todasaspatas_api.form_type.adoption_request_message_response:
        class: "%todasaspatas_api.form_type.adoption_request_message_response.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_adoptionrequestmessage_response }
            
    todasaspatas_api.form_type.question_message_response:
        class: "%todasaspatas_api.form_type.question_message_response.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_questionmessage_response }
            
    todasaspatas_api.form_type.favorite_pet:
        class: "%todasaspatas_api.form_type.favorite_pet.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_favorite_pet }
            
    todasaspatas_api.form_type.user_common:
        class: "%todasaspatas_api.form_type.user_common.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_usercommon }
            
    todasaspatas_api.form_type.user_common_api:
        class: "%todasaspatas_api.form_type.user_common_api.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_usercommon_api }
            
    todasaspatas_api.form_type.client:
        class: "%todasaspatas_api.form_type.client.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_client }
            
    todasaspatas_api.form_type.pet_adoption:
        class: "%todasaspatas_api.form_type.pet_adoption.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_petadoption }
            
    todasaspatas_api.form_type.pet_image:
        class: "%todasaspatas_api.form_type.pet_image.class%"
        arguments: [false]
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_petimage }
            
    todasaspatas_api.form_type.pet_image_creating:
        class: "%todasaspatas_api.form_type.pet_image.class%"
        arguments: [true]
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_petimage_creating }
            
    todasaspatas_api.form_type.pet:
        class: "%todasaspatas_api.form_type.pet.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_pet }
            
    todasaspatas_api.form_type.breed:
        class: "%todasaspatas_api.form_type.breed.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_breed }
            
    todasaspatas_api.form_type.organization:
        class: "%todasaspatas_api.form_type.organization.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_organization }
            
    todasaspatas_api.form_type.user_organization:
        class: "%todasaspatas_api.form_type.user_organization.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_userorganization }
            
    todasaspatas_api.form_type.user_admin:
        class: "%todasaspatas_api.form_type.user_admin.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_useradmin }
            
    todasaspatas_api.form_type.user_admin_profile:
        class: "%todasaspatas_api.form_type.user_admin_profile.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_useradminprofile }
            
    todasaspatas_api.form_type.group:
        class: "%todasaspatas_api.form_type.group.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_group }
            
    todasaspatas_api.form_type.text:
        class: "%todasaspatas_api.form_type.text.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_text }
            
    todasaspatas_api.form_type.address:
        class: "%todasaspatas_api.form_type.address.class%"
        arguments: ["@app.repository.city"]
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_address }
            
    todasaspatas_api.form_type.city:
        class: "%todasaspatas_api.form_type.city.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_city }
            
    todasaspatas_api.form_type.state_city:
        class: "%todasaspatas_api.form_type.state_city.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_state_city }
            
    todasaspatas_api.form_type.state:
        class: "%todasaspatas_api.form_type.state.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_state }
            
    todasaspatas_api.form_type.country:
        class: "%todasaspatas_api.form_type.country.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_country }