parameters:
    todasaspatas_api.form_type.user_admin.class: TodasAsPatas\ApiBundle\Form\UserAdminType
    todasaspatas_api.form_type.user_admin_profile.class: TodasAsPatas\ApiBundle\Form\UserAdminProfileType
    todasaspatas_api.form_type.group.class: TodasAsPatas\ApiBundle\Form\GroupType
    todasaspatas_api.form_type.country.class: TodasAsPatas\ApiBundle\Form\CountryType
    todasaspatas_api.form_type.state.class: TodasAsPatas\ApiBundle\Form\StateType
    todasaspatas_api.form_type.state_city.class: TodasAsPatas\ApiBundle\Form\StateCityType
    todasaspatas_api.form_type.city.class: TodasAsPatas\ApiBundle\Form\CityType
    todasaspatas_api.form_type.address.class: TodasAsPatas\ApiBundle\Form\AddressType
    todasaspatas_api.form_type.text.class: TodasAsPatas\ApiBundle\Form\TextType
    todasaspatas_api.form_type.user_organization.class: TodasAsPatas\ApiBundle\Form\UserOrganizationType
    todasaspatas_api.form_type.organization.class: TodasAsPatas\ApiBundle\Form\OrganizationType

services:
    todasaspatas_api.form_type.organization:
        class: "%todasaspatas_api.form_type.organization.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_organization }
            
    todasaspatas_api.form_type.user_organization:
        class: "%todasaspatas_api.form_type.user_organization.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_userorganization }
            
    todasaspatas_api.form_type.user_admin:
        class: "%todasaspatas_api.form_type.user_admin.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_useradmin }
            
    todasaspatas_api.form_type.user_admin_profile:
        class: "%todasaspatas_api.form_type.user_admin_profile.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_useradminprofile }
            
    todasaspatas_api.form_type.group:
        class: "%todasaspatas_api.form_type.group.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_group }
            
    todasaspatas_api.form_type.text:
        class: "%todasaspatas_api.form_type.text.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_text }
            
    todasaspatas_api.form_type.address:
        class: "%todasaspatas_api.form_type.address.class%"
        arguments: ["@app.repository.city"]
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_address }
            
    todasaspatas_api.form_type.city:
        class: "%todasaspatas_api.form_type.city.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_city }
            
    todasaspatas_api.form_type.state_city:
        class: "%todasaspatas_api.form_type.state_city.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_state_city }
            
    todasaspatas_api.form_type.state:
        class: "%todasaspatas_api.form_type.state.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_state }
            
    todasaspatas_api.form_type.country:
        class: "%todasaspatas_api.form_type.country.class%"
        tags:
            - { name: form.type, alias: todasaspatas_apibundle_country }