parameters:
    todasaspatas_api.event_listener.country_subscriber.class: TodasAsPatas\ApiBundle\EventListener\CountrySubscriber
    todasaspatas_api.event_listener.state_subscriber.class: TodasAsPatas\ApiBundle\EventListener\StateSubscriber
    todasaspatas_api.event_listener.pet_subscriber.class: TodasAsPatas\ApiBundle\EventListener\PetSubscriber
    todasaspatas_api.event_listener.petadoption_subscriber.class: TodasAsPatas\ApiBundle\EventListener\PetAdoptionSubscriber
    todasaspatas_api.event_listener.organization_subscriber.class: TodasAsPatas\ApiBundle\EventListener\OrganizationSubscriber
    todasaspatas_api.event_listener.pet_listener_subscriber.class: TodasAsPatas\ApiBundle\EventListener\PetListenerSubscriber

services:
    oauth_event_listener:
        class:  TodasAsPatas\ApiBundle\EventListener\OAuthEventListener
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
            
    todasaspatas_api.event_listener.pet_listener_subscriber:
        class: "%todasaspatas_api.event_listener.pet_listener_subscriber.class%"
        arguments: [@service_container, '']
        tags:
            - { name: kernel.event_subscriber }
            
    todasaspatas_api.event_listener.petadoption_subscriber:
        class: "%todasaspatas_api.event_listener.petadoption_subscriber.class%"
        tags:
            - { name: kernel.event_subscriber }
            
    todasaspatas_api.event_listener.organization_subscriber:
        class: "%todasaspatas_api.event_listener.organization_subscriber.class%"
        arguments: ["@app.repository.userorganization", "@app.manager.userorganization"]
        tags:
            - { name: kernel.event_subscriber }
    
    todasaspatas_api.event_listener.pet_subscriber:
        class: "%todasaspatas_api.event_listener.pet_subscriber.class%"
        arguments: ["@app.repository.petimage", "@app.manager.petimage"]
        tags:
            - { name: kernel.event_subscriber }
    
    todasaspatas_api.event_listener.state_subscriber:
        class: "%todasaspatas_api.event_listener.state_subscriber.class%"
        arguments: ["@app.repository.city", "@app.manager.city"]
        tags:
            - { name: kernel.event_subscriber }
    
    todasaspatas_api.event_listener.country_subscriber:
        class: "%todasaspatas_api.event_listener.country_subscriber.class%"
        arguments: ["@app.repository.state", "@app.manager.state"]
        tags:
            - { name: kernel.event_subscriber }