TodasAsPatas\ApiBundle\Entity\Breed:
    properties:
        name:
            - NotBlank: ~
            
TodasAsPatas\ApiBundle\Entity\UserOrganization:
    properties:
        organization:
            - NotNull: ~
            
TodasAsPatas\ApiBundle\Entity\Organization:
    properties:
        name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        phone:
            - NotBlank: ~
            - Length:
                min: 10
                max: 11
        address:
            - NotNull: ~
            - Valid: ~
        users:
            - NotNull: ~
            - Valid: ~

TodasAsPatas\ApiBundle\Entity\Text:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: typeId
    properties:
        title:
            - NotBlank: ~
        content:
            - NotBlank: ~
        typeId:
            - NotBlank: ~

TodasAsPatas\ApiBundle\Entity\User:
    constraints:
        - ByteinCoffee\ExtraBundle\Validator\UniqueEntity: 
            fields: [email]
            errorPath: email
            message: 'Esse email já está sendo utiizado!'
            repositoryClass: TodasAsPatas\ApiBundle\Entity\User
        - ByteinCoffee\ExtraBundle\Validator\UniqueEntity: 
            fields: [username]
            errorPath: username
            message: 'Esse username já está sendo utiizado!'
            repositoryClass: TodasAsPatas\ApiBundle\Entity\User
    getters:
        passwordValid:
            - 'True':
                message: O campo senha é obrigatório.
    properties:
        username:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        
TodasAsPatas\ApiBundle\Entity\Group:
    properties:
        name:
            - NotBlank: ~
            
TodasAsPatas\ApiBundle\Entity\Address:
    properties:
        number:
            - NotBlank: ~
            - NotNull: ~
        postalCode:
            - NotBlank: ~
        street:
            - NotBlank: ~
        district:
            - NotBlank: ~
        city:
            - NotNull: ~
            
TodasAsPatas\ApiBundle\Entity\City:
    properties:
        name:
            - NotBlank: ~
                
TodasAsPatas\ApiBundle\Entity\State:
    properties:
        cities:
            - Valid: ~
        name:
            - NotBlank: ~
        acronym:
            - NotBlank: ~
            - Length:
                min: 2
                max: 2
            
TodasAsPatas\ApiBundle\Entity\Country:
    properties:
        states:
            - Valid: ~
            - NotNull: ~
        name:
            - NotBlank: ~