TodasAsPatas\ApiBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        username:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
            
TodasAsPatas\ApiBundle\Entity\Group:
    properties:
        name:
            - NotBlank: ~
            
TodasAsPatas\ApiBundle\Entity\Address:
    properties:
        number:
            - NotBlank: ~
            - NotNull: ~
        postalCode:
            - NotBlank: ~
        street:
            - NotBlank: ~
        district:
            - NotBlank: ~
        city:
            - NotNull: ~
            
TodasAsPatas\ApiBundle\Entity\City:
    properties:
        name:
            - NotBlank: ~
                
TodasAsPatas\ApiBundle\Entity\State:
    properties:
        cities:
            - Valid: ~
        name:
            - NotBlank: ~
        acronym:
            - NotBlank: ~
            - Length:
                min: 2
                max: 2
            
TodasAsPatas\ApiBundle\Entity\Country:
    properties:
        states:
            - Valid: ~
            - NotNull: ~
        name:
            - NotBlank: ~